/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clinicaCaracas;

import javax.swing.JOptionPane;

/**
 *
 * @author alons
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    
    public static String clientes ="";
    public static Lista listacliente = new Lista();
    public static int cantC = 0;
    public static double montoNet =0;
    public Registro() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexo = new javax.swing.ButtonGroup();
        seguro = new javax.swing.ButtonGroup();
        tipoestudio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputCI = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputEdad = new javax.swing.JTextField();
        masc = new javax.swing.JRadioButton();
        Fem = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        siseg = new javax.swing.JRadioButton();
        noseg = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        resonancia = new javax.swing.JRadioButton();
        ultrasonido = new javax.swing.JRadioButton();
        tomografía = new javax.swing.JRadioButton();
        registrarcliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR CLIENTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 220, 30));

        jLabel2.setText("Edad:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 50, 20));

        inputCI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCIActionPerformed(evt);
            }
        });
        jPanel1.add(inputCI, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 200, -1));

        jLabel3.setText("Cédula:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 50, 20));
        jPanel1.add(inputEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, -1));

        sexo.add(masc);
        masc.setText("Masculino");
        jPanel1.add(masc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        sexo.add(Fem);
        Fem.setText("Femenino");
        jPanel1.add(Fem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jLabel4.setText("Sexo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel5.setText("Tipo de estudio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, -1, -1));

        seguro.add(siseg);
        siseg.setText("sí");
        jPanel1.add(siseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        seguro.add(noseg);
        noseg.setText("No");
        jPanel1.add(noseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel6.setText("Posee seguro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        tipoestudio.add(resonancia);
        resonancia.setText("Resonancia");
        jPanel1.add(resonancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, -1, -1));

        tipoestudio.add(ultrasonido);
        ultrasonido.setText("Ultrasonido");
        jPanel1.add(ultrasonido, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        tipoestudio.add(tomografía);
        tomografía.setText("Tomografía");
        jPanel1.add(tomografía, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        registrarcliente.setText("Registrar cliente");
        registrarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarclienteActionPerformed(evt);
            }
        });
        jPanel1.add(registrarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputCIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCIActionPerformed

    }//GEN-LAST:event_inputCIActionPerformed

    private void registrarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarclienteActionPerformed
        // TODO add your handling code here:
        Functions func = new Functions();
        String sexo = "";
        String seguro = "";
        String tipoest = "";
        Long ci = null;
        int precio = 0;
        int edad = 0;
        if (Fem.isSelected()){
            sexo = "Fem";
        }else{
            sexo = "Masc";
        }
        
        try{
            ci = Long.parseLong(inputCI.getText());
            edad = Integer.parseInt(inputEdad.getText());
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Datos inválidos");
        }
        if (siseg.isSelected()){seguro = "Sí";}
        else{seguro = "No";}
        
        if(ultrasonido.isSelected()){
            tipoest = "Ultrasonido";
            precio = 100;
        }
        else if(resonancia.isSelected()){
            tipoest = "Resonancia";
            precio = 130;
        }
        else{
            tipoest = "Tomografía";
            precio = 160;
        }
        double monto = func.Finalmonto(precio, edad, sexo, seguro);
        montoNet += monto;
        Cliente cliente = new Cliente(ci, edad, sexo, seguro, tipoest);
        listacliente.append(cliente);
        cantC += 1;
        clientes = "CI: "+ci+"\n"+"Edad: "+edad+"\n"+"Sexo: "+sexo + "\n"+"Seguro: "+ seguro+"\n"+"Tipo de estudio: "+tipoest+ "Monto final: "+ monto;
        this.dispose();
        Recibo recibo = new Recibo(this);
        recibo.setVisible(true);
        
    }//GEN-LAST:event_registrarclienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Fem;
    private javax.swing.JTextField inputCI;
    private javax.swing.JTextField inputEdad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton masc;
    private javax.swing.JRadioButton noseg;
    private javax.swing.JButton registrarcliente;
    private javax.swing.JRadioButton resonancia;
    private javax.swing.ButtonGroup seguro;
    private javax.swing.ButtonGroup sexo;
    private javax.swing.JRadioButton siseg;
    private javax.swing.ButtonGroup tipoestudio;
    private javax.swing.JRadioButton tomografía;
    private javax.swing.JRadioButton ultrasonido;
    // End of variables declaration//GEN-END:variables
}
